In [1]:
import os
import pandas as pd
import numpy as np
import geopandas as gpd

In [2]:
# set option to see all data frame columns
pd.set_option('display.max_columns', None)

In [3]:
marin = gpd.read_parquet("../../../../../../capstone/electrigrid/data/linked.parquet")

In [4]:
marin.head()

,ID,unit,geometry,circuit_id,segment_id,GenCapacit,dist_to_line_m,GEOID_right,length_m,units_by_tract,max_gen,total_feeder_length,perc_length,home_count_seg,home_count_circuit,perc_homes,tothh_Cpoly,DER_max_Cpoly,_hhWt,_hhWt_n,DER_remain
0,4147850,1.0,POINT (-122.53161 37.89284),042031122,3646706,0.91,996.304761,06041126100,4.579618,1072.0,0.91,219147.707288,0.00209,624.0,5706.0,10.935857,1072.0,757.26,142.268265,2.806009e-04,0.000262
1,4147677,2.0,POINT (-122.53446 37.89396),042031122,3646706,0.91,991.651477,06041128200,4.579618,11.0,0.91,219147.707288,0.00209,624.0,5706.0,10.935857,11.0,6.37,0.012280,2.422040e-08,0.000002
2,4147673,1.0,POINT (-122.53457 37.89444),042031122,3646706,0.91,953.106054,06041128200,4.579618,11.0,0.91,219147.707288,0.00209,624.0,5706.0,10.935857,11.0,6.37,0.012280,2.422040e-08,0.000002
3,4147690,2.0,POINT (-122.53496 37.89453),042031122,3646706,0.91,965.440318,06041128200,4.579618,11.0,0.91,219147.707288,0.00209,624.0,5706.0,10.935857,11.0,6.37,0.012280,2.422040e-08,0.000002
4,4147672,1.0,POINT (-122.53545 37.89475),042031122,3646706,0.91,973.958291,06041128200,4.579618,11.0,0.91,219147.707288,0.00209,624.0,5706.0,10.935857,11.0,6.37,0.012280,2.422040e-08,0.000002

In [6]:
pge = gpd.read_file("../../../../../../capstone/electrigrid/data/fig1sourcedata/PGE_limitsdemo.csv")

In [8]:
pge = pge[pge['CircuitName'] == "ALTO 1120"]

In [9]:
pge.head()

,Cpoly,CircuitName,GEOID10,ICL_kWphh,ICPVOF_kWphh,ICPV_kWphh,ICUGOF_kWphh,ICUG_kWphh,ICL_kWphh_cap,ICPVOF_kWphh_cap,ICPV_kWphh_cap,ICUGOF_kWphh_cap,ICUG_kWphh_cap,ICPVOF_e_kWphh,ICPV_e_kWphh,ICUGOF_e_kWphh,ICUG_e_kWphh,ICPVOF_e_kWphh_cap,ICPV_e_kWphh_cap,ICUGOF_e_kWphh_cap,ICUG_e_kWphh_cap,CircVolt_kV,Length_m,Length_m_ctot,ICA_pct,ResCust,Res_pct,Com_pct,Ind_pct,Agr_pct,Oth_pct,tothh_Cpoly,tothh_ctot,tothh_pct,tothh_perkm,SAIDI5yravg,urbanheat_pctl,ghi_kWhpm2day,tothh,racediversity,black_pct,asian_pct,nlxwhite_pct,latinx_pct,inc50kbelow_pct,inc150kplus_pct,medhhinc,edavgyrs,ownerocc_pct,singleunit_pct,unitsavg,medyrbuilt,hhdensity_fctr,hhdensity_hhsqkm,polexposure_pctl,polenvt_pctl,popsens_pctl,lingisolation_pctl,sb535disad,ObjectID,geometry
179,060411262002 ALTO 1120,ALTO 1120,60411262002,1.965474826,0.961711218,4.810684076,0.269814501,8.078189403,1.965474826,0.961711218,4.810684076,0.269814501,8.078189403,1.754832035,5.603804893,1.062935317,8.871310219,1.754832035,5.603804893,1.062935317,8.871310219,12,9056.69225,79370.34359,0.889830508,3801,90.5431,6.55074,2.52501,0,0.38113,430.2325413,3618.616408,0.204119958,47.50437902,170.86,10.47133441,4.6559997,985,0.179301471,0.005165289,0.039772727,0.785123967,0.14411157,0.402030457,0.304568528,82014,16.11904762,0.519796954,0.378680203,17.82385787,1969,urban,890.8876997,27.55008454,36.67567829,5.597761555,16.65111318,No,180,None
180,060411261003 ALTO 1120,ALTO 1120,60411261003,0.125250847,0.832358247,0.711981243,0.269814501,0.557395069,0.125250847,0.832358247,0.711981243,0.269814501,0.557395069,1.625479064,1.50510206,1.062935317,1.350515885,1.625479064,1.50510206,1.062935317,1.350515885,12,749.9010162,79370.34359,1,3801,90.5431,6.55074,2.52501,0,0.38113,32.6392037,3618.616408,0.015485377,43.52468258,170.86,12.6601169,5.088,479,0.02923844,0,0,0.97446458,0.010708402,0.229645094,0.532359081,171076,16.22764228,0.597077244,0.762004175,3.044885177,1943,urban,1446.317417,19.31273864,22.34056678,7.208433793,2.59965338,No,181,None
181,060411282003 ALTO 1120,ALTO 1120,60411282003,1.965474826,0.961711218,4.810684076,0.269814501,1.49446504,1.965474826,0.961711218,4.810684076,0.269814501,1.49446504,1.754832035,5.603804893,1.062935317,2.287585856,1.754832035,5.603804893,1.062935317,2.287585856,12,3238.996811,79370.34359,0.580645161,3801,90.5431,6.55074,2.52501,0,0.38113,88.20491797,3618.616408,0.04184803,27.23217191,170.86,7.051361771,4.6559997,781,0.330484366,0.056277056,0.105339105,0.78018278,0.042809043,0.166453265,0.445582586,121875,16.38830898,0.661971831,0.903703704,1.340123457,1958,suburban,808.0348879,17.68680769,36.81636261,14.77559369,8.99880016,No,182,None
182,060411270001 ALTO 1120,ALTO 1120,60411270001,0.125250847,0.832358247,0.711981243,0.269814501,0.525082311,0.125250847,0.832358247,0.711981243,0.269814501,0.525082311,1.625479064,1.50510206,1.062935317,1.318203128,1.625479064,1.50510206,1.062935317,1.318203128,12,230.1470032,79370.34359,1,3801,90.5431,6.55074,2.52501,0,0.38113,1.4419944,3618.616408,0.000684141,6.265536288,170.86,14.14003233,5.088,578,0.186188429,0,0.045527157,0.752396166,0.146964856,0.287197232,0.216262976,83750,15.5536105,0.487889273,0.604195804,2.18951049,1951,urban,1229.09125,15.03322583,21.88857705,10.04664328,18.38421544,No,183,None
183,060411250001 ALTO 1120,ALTO 1120,60411250001,1.965474826,0.961711218,4.810684076,0.269814501,5.800139991,1.965474826,0.961711218,4.810684076,0.269814501,5.800139991,1.754832035,5.603804893,1.062935317,6.593260808,1.754832035,5.603804893,1.062935317,6.593260808,12,11324.65059,79370.34359,0.882352941,3801,90.5431,6.55074,2.52501,0,0.38113,197.6164756,3618.616408,0.093757359,17.45011682,170.86,6.26787713,4.6559997,572,0.221932619,0.011284722,0.057291667,0.846354167,0.047743056,0.229020979,0.527972028,166167,16.56584362,0.575174825,0.562706271,10.81270627,1976,suburban,323.3339662,26.84432974,24.38087137,12.11032827,23.27689641,No,184,None

In [16]:
pge['ICL_kWphh'] = pd.to_numeric(pge['ICL_kWphh'])

In [18]:
pge['ICL_kWphh'].describe()

count    11.000000
mean      1.630889
std       0.744407
min       0.125251
25%       1.965475
50%       1.965475
75%       1.965475
max       1.965475
Name: ICL_kWphh, dtype: float64

In [14]:
marin['DER_remain'].describe()

count    4703.000000
mean        0.000175
std         0.000072
min         0.000000
25%         0.000155
50%         0.000155
75%         0.000243
max         0.000262
Name: DER_remain, dtype: float64

In [20]:
len(marin)

4703

In [21]:
marin['circuit_id'].unique()

array(['042031122'], dtype=object)