In [1]:
import pandas as pd
import geopandas as gpd
import os

In [2]:
os.environ['PROJ_LIB'] = '/opt/anaconda3/share/proj'

In [3]:
cust = pd.read_csv("../../../../../../capstone/electrigrid/data/utilities/sce_circuits/ICA_Single_Consolidated_Table.csv")

In [4]:
cust.head()

,circuit_name,circuit_id,circuit_voltage,percent_15_cap,res_pct,com_pct,agr_pct,other_pct,ind_pct,sub_name,...,total_gen,projected_load,penetration_level,max_remain_cap,agr_total,com_total,ind_total,res_total,other_total,OBJECTID
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jose,...,0.0,5.00,0.0,5.0,NaN,NaN,NaN,NaN,NaN,1
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Julian Hinds,...,0.0,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,2
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Glow,...,0.0,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,3
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Growers,...,0.0,0.00,0.0,0.0,NaN,NaN,NaN,NaN,NaN,4
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Haagen,...,0.0,4.79,0.0,5.6,NaN,NaN,NaN,NaN,NaN,5

In [5]:
cust['res_pct'].nunique()

2814

In [14]:
len(pd.isna(cust['res_pct']))

5724

In [7]:
# Load data
sce_circuits = gpd.read_parquet("../../../../../../capstone/electrigrid/data/utilities/sce_circuits/ica_circuit_segments.parquet")

In [12]:
len(sce_circuits.groupby('circuit_name'))

3702

In [15]:
len(pd.notna(cust['res_pct']))

5724

In [10]:
sce_circuits.head()

,note,most_limiting_criteria_pv_of,circuit_name,most_limiting_criteria_pv_sg,changed_date,ica_overall_pv,most_limiting_criteria_ug_of,circuit_voltage,section_id,uniform_generation_op_flex,...,most_limiting_criteria_lsg,system_name,most_limiting_criteria_ug_sg,download_link,ica_overall_load,lgp_flag,SHAPE__Length,objectid,node_id,geometry
0,None,Operational Flexibility,Abana,Steady State Voltage,01/08/2025,6.0,Operational Flexibility,12,12369095,.7567,...,Thermal,Del Amo 220/66 System,Steady State Voltage,https://drpep.sce.com/icafiledownload/models/w...,3.67,No,220.586328,1,12368407,"LINESTRING (-118.05521 33.88651, -118.05523 33..."
1,None,Operational Flexibility,Abana,Thermal,01/08/2025,7.0,Operational Flexibility,12,12368778,.7567,...,Thermal,Del Amo 220/66 System,Steady State Voltage,https://drpep.sce.com/icafiledownload/models/w...,3.67,No,13.151411,2,77150492,"LINESTRING (-118.05065 33.88036, -118.05065 33..."
2,None,Operational Flexibility,Abana,Steady State Voltage,01/08/2025,7.0,Operational Flexibility,12,12368715,.7567,...,Thermal,Del Amo 220/66 System,Steady State Voltage,https://drpep.sce.com/icafiledownload/models/w...,3.67,No,486.668873,3,12358595,"LINESTRING (-118.05517 33.88518, -118.05521 33..."
3,None,Operational Flexibility,Abana,Thermal,01/08/2025,3.0,Operational Flexibility,12,196305182,.7567,...,Thermal,Del Amo 220/66 System,Steady State Voltage,https://drpep.sce.com/icafiledownload/models/w...,2.53,No,9.081920,4,12367916,"LINESTRING (-118.05587 33.88595, -118.05584 33..."
4,None,Operational Flexibility,Abana,Thermal,01/08/2025,7.0,Operational Flexibility,12,12368868,.7567,...,Thermal,Del Amo 220/66 System,Steady State Voltage,https://drpep.sce.com/icafiledownload/models/w...,3.67,No,217.281367,5,12368547,"LINESTRING (-118.05260 33.88037, -118.05331 33..."