In [22]:
import geopandas as gpd
import pandas as pd

# set option to see all data frame columns
pd.set_option('display.max_columns', None)

In [6]:
networked = gpd.read_file("../../../../../../capstone/electrigrid/data/utilities/pge_shapefiles/NetworkedSecondaryBuffer.shp")

In [7]:
networked.head()

,Label,Publish,Last_Updat,SHAPE_Leng,SHAPE_Area,geometry
0,NetworkedSecondaryBuffer,1,2025-06-02,14446.569570,7.756554e+06,"POLYGON ((553726.963 4183158.069, 553736.930 4..."
1,NetworkedSecondaryBuffer,1,2025-06-02,11698.186321,4.206894e+06,"POLYGON ((563010.555 4183284.528, 562997.697 4..."

In [8]:
ed_sub = gpd.read_file("../../../../../../capstone/electrigrid/data/utilities/pge_shapefiles/EDSubstations.shp")

In [9]:
ed_sub.head()

,Substation,Substati_1,Voltage_kV,NUMBANKS,REDACTED,UNGROUNDED,Division,Existing_D,Queued_DG,Total_DG,Publish,Last_Updat,geometry
0,LAMONT,25391,12,2,Yes,None,Kern,18400,28060,46460,1,2025-06-02,POINT (876359.283 3913857.542)
1,POTTER VALLEY P H,04228,12,3,No,None,Humboldt,540,90,630,1,2025-06-02,POINT (488962.642 4356858.433)
2,HIGHWAY,04265,12,2,No,None,North Bay,12855,15529,28384,1,2025-11-20,POINT (565363.608 4224489.060)
3,KING CITY,18203,12,3,No,None,Central Coast,2628,2835,5463,1,2025-11-18,POINT (668370.524 4009649.909)
4,BELLE HAVEN,02402,4.16,5,Yes,None,Peninsula,17400,4760,22160,1,2025-06-02,POINT (573511.216 4148239.891)

In [10]:
df_sub = gpd.read_file("../../../../../../capstone/electrigrid/data/utilities/pge_shapefiles/DFSubstationArea___PeakFacilityLoadingPercent.shp")

In [11]:
df_sub.head()

,substation,gnaneedid,division,gnafacilit,bankname,substati_1,facilityty,facilityra,facilitylo,facility_1,facility_2,facility_3,facility_4,peakfacili,idnumber,last_updat,publish,geometry
0,02402,GNA_0240201_Capacity,Peninsula,BELLE HAVEN BANK 1,BELLE HAVEN BANK 1,BELLE HAVEN,BANK,7.05,6.52,6.49,6.51,6.64,6.85,97.11,0240201,2025-08-29,1,POINT (-13599745.782 4505964.247)
1,02402,GNA_0240202_Capacity,Peninsula,BELLE HAVEN BANK 2,BELLE HAVEN BANK 2,BELLE HAVEN,BANK,7.05,9.14,9.25,9.46,9.69,9.97,141.41,0240202,2025-08-29,1,POINT (-13599745.782 4505964.247)
2,02402,GNA_0240203_Capacity,Peninsula,BELLE HAVEN BANK 3,BELLE HAVEN BANK 3,BELLE HAVEN,BANK,15.84,17.34,19.94,21.26,21.11,21.04,134.22,0240203,2025-08-29,1,POINT (-13599745.782 4505964.247)
3,02402,GNA_0240204_Capacity,Peninsula,BELLE HAVEN BANK 4,BELLE HAVEN BANK 4,BELLE HAVEN,BANK,10.40,9.59,9.48,9.39,9.36,9.33,92.20,0240204,2025-08-29,1,POINT (-13599745.782 4505964.247)
4,02402,GNA_0240205_Capacity,Peninsula,BELLE HAVEN BANK 5,BELLE HAVEN BANK 5,BELLE HAVEN,BANK,29.69,25.06,24.56,24.84,25.14,25.65,86.38,0240205,2025-08-29,1,POINT (-13599745.782 4505964.247)

In [13]:
igp = gpd.read_file("../../../../../../capstone/electrigrid/data/utilities/pge_shapefiles/igp_tline.shp")

In [14]:
igp.head()

,OBJECTID,PROJECT_NA,RATING,PGE,CAISO,CPUC,Approval,CONSTRUCTI,Projected_,publish,Last_Updat,SHAPE_Leng,geometry
0,1,Rio Oso 230/115 kV Transformer Upgrades,230/115,2017,2007,N/A,PGE/CAISO,Construction,May-2025,1,20250415232159,17703.416138,"LINESTRING (632809.295 4310629.003, 632772.816..."
1,2,Round Mountain 500 kV Dynamic Support,500,2022,2019,N/A,PGE/CAISO,Construction,Jun-2025,1,20250415232246,143279.749815,"LINESTRING (589793.960 4517853.534, 589775.745..."
2,3,Contra Costa PP 230 kV Line Terminals Reconfig...,230,2023,2022,N/A,PGE/CAISO,Engineering,Sep-2025,1,20250415232246,29714.002340,"LINESTRING (608848.324 4208185.055, 608836.825..."
3,4,Contra Costa PP 230 kV Line Terminals Reconfig...,230,2023,2022,N/A,PGE/CAISO,Engineering,Sep-2025,1,20250415232246,9029.940523,"LINESTRING (608609.471 4208182.365, 608605.857..."
4,5,Contra Costa PP 230 kV Line Terminals Reconfig...,230,2023,2022,N/A,PGE/CAISO,Engineering,Sep-2025,1,20250415232246,16421.436813,"LINESTRING (602572.896 4220321.616, 602593.040..."

In [15]:
gna_sub= gpd.read_file("../../../../../../capstone/electrigrid/data/utilities/pge_shapefiles/GNASubstationArea__PeakFacilityDeficiencyPercent.shp")

In [16]:
gna_sub.head()

,division,substation,gnaneedid,facilityid,gnafacilit,bankname,substati_1,facilityty,primarydri,distributi,anticipate,peakfacili,last_updat,publish,deficiency,deficien_1,deficien_2,deficien_3,deficien_4,geometry
0,Diablo,01202,GNA_0120201_Capacity,0120201,CLAYTON BANK 1,CLAYTON BANK 1,CLAYTON,BANK,None,None,None,0,2025-08-29,1,0,0,0,0,0,POINT (-13577557.788 4571559.529)
1,Diablo,01202,GNA_0120202_Capacity,0120202,CLAYTON BANK 2,CLAYTON BANK 2,CLAYTON,BANK,None,None,None,0,2025-08-29,1,0,0,0,0,0,POINT (-13577557.788 4571559.529)
2,Diablo,01202,GNA_0120203_Capacity,0120203,CLAYTON BANK 3,CLAYTON BANK 3,CLAYTON,BANK,None,None,None,0,2025-08-29,1,0,0,0,0,0,POINT (-13577557.788 4571559.529)
3,Diablo,01202,GNA_0120205_Capacity,0120205,CLAYTON BANK 5,CLAYTON BANK 5,CLAYTON,BANK,None,None,None,0,2025-08-29,1,0,0,0,0,0,POINT (-13577557.788 4571559.529)
4,East Bay,01204,GNA_0120403_Capacity,0120403,OAKLAND D BANK 3,OAKLAND D BANK 3,OAKLAND D,BANK,None,None,None,-99.99,2025-08-29,1,-99.99,-99.99,-99.99,-99.99,-99.99,POINT (-13610098.876 4556492.567)

In [17]:
transmission = gpd.read_file("../../../../../../capstone/electrigrid/data/utilities/pge_shapefiles/TransmissionLines.shp")

In [18]:
transmission.head()

,TLINE_NAME,RATEDKV,SAP_FUNC_L,Publish,Last_Updat,SHAPE_Leng,geometry
0,ELLIS TAP,115,ETL.4021,1,2025-06-02,264.492667,"LINESTRING (627814.093 4176121.829, 627812.880..."
1,PINE FLAT PH TAP (CDWR),230,ETL.4821,1,2025-06-02,1280.008073,"LINESTRING (827593.490 4082587.267, 827454.596..."
2,CHRISTIE-WILLOW PASS,60,ETL.6370,1,2025-06-02,25586.274812,"LINESTRING (569473.790 4206455.380, 569460.010..."
3,MIDSET TAP,115,ETL.1581,1,2025-06-02,1166.071797,"LINESTRING (812224.925 3898824.642, 812226.774..."
4,PITTSBURG-DELTA ENERGY CENTER #2,230,ETL.3315,1,2025-06-02,2116.634057,"LINESTRING (599266.874 4208990.901, 599268.380..."

In [19]:
df_circ = gpd.read_file("../../../../../../capstone/electrigrid/data/utilities/pge_shapefiles/DFCircuitsView.shp")

In [23]:
df_circ.head()

,substation,gnaneedid,division,gnafacilit,bankname,substati_1,facilityra,idnumber,last_updat,facilityty,facilitylo,facility_1,facility_2,facility_3,facility_4,peakfacili,publish,circuitid,circuitnam,Shape_Leng,geometry
0,12041,GNA_012041102_Capacity,East Bay,OAKLAND D 1102,OAKLAND D BANK 5,OAKLAND D,7.48,12041102,2025-08-29,FEEDER,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,1,012041102,OAKLAND D 1102,10124.019833,"MULTILINESTRING ((-13613137.245 4555900.310, -..."
1,01201,GNA_012011101_Capacity,East Bay,OAKLAND C 1101,NETWORK GROUP OAKLAND C 1251,OAKLAND C,9.14,012011101,2025-08-29,FEEDER,5.89,5.86,5.83,5.80,6.05,66.18,1,012011101,OAKLAND C 1101,5111.350800,"MULTILINESTRING ((-13611295.137 4551493.467, -..."
2,01201,GNA_012011102_Capacity,East Bay,OAKLAND C 1102,NETWORK GROUP OAKLAND C 1251,OAKLAND C,10.27,012011102,2025-08-29,FEEDER,2.44,2.41,2.39,2.39,2.40,23.71,1,012011102,OAKLAND C 1102,6255.822658,"MULTILINESTRING ((-13611186.650 4551700.744, -..."
3,01201,GNA_012011103_Capacity,East Bay,OAKLAND C 1103,NETWORK GROUP OAKLAND C 1251,OAKLAND C,9.14,012011103,2025-08-29,FEEDER,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,1,012011103,OAKLAND C 1103,4976.465247,"MULTILINESTRING ((-13611265.308 4551681.330, -..."
4,01201,GNA_012011104_Capacity,East Bay,OAKLAND C 1104,NETWORK GROUP OAKLAND C 1251,OAKLAND C,9.14,012011104,2025-08-29,FEEDER,-99.99,-99.99,-99.99,-99.99,-99.99,-99.99,1,012011104,OAKLAND C 1104,5661.327582,"MULTILINESTRING ((-13611069.543 4551771.621, -..."

In [25]:
feeder_load = gpd.read_file("../../../../../../capstone/electrigrid/data/utilities/pge_shapefiles/FeederLoadProfile.shp")

In [26]:
feeder_load.head()

,OBJECTID,FeederID,MonthHour,division,Low,High,Publish,Last_Updat,geometry
0,1,12232107,12_10,Mission,8168.0,11718.0,1,20250602010025,None
1,2,163451701,05_02,Stockton,1418.0,1576.0,1,20251121081319,None
2,3,163121103,10_23,Stockton,1214.0,2134.0,1,20251121081258,None
3,4,253391104,02_01,Kern,1947.0,2199.0,1,20251121081319,None
4,5,12041134,12_06,East Bay,2193.0,2802.0,1,20251121081320,None

In [27]:
known_load = gpd.read_file("../../../../../../capstone/electrigrid/data/utilities/pge_shapefiles/KnownLoad.shp")

In [28]:
known_load.head()

,Circuitid,CircuitNam,Unique_Ide,Type,Category,SUBNAME,IEPR_Statu,Expected_L,Status,Completed_,publish,Last_Updat,SHAPE_Leng,geometry
0,083701101,STONE 1101,35510745,Residential,Home Construction,STONE,N/A,CC,Monitor Load,No,1,2025-09-12,40036.450209,"MULTILINESTRING ((596720.071 4127966.886, 5967..."
1,013501101,JARVIS 1101,35612424,Residential,Home Construction,JARVIS,N/A,CC,Service Requested,No,1,2025-09-12,50371.426963,"MULTILINESTRING ((583419.281 4164617.189, 5834..."
2,082952113,EDENVALE 2113,35615107,Residential,Home Construction,EDENVALE,N/A,CC,Service Requested,No,1,2025-09-12,54801.713172,"MULTILINESTRING ((603890.097 4122288.322, 6038..."
3,253372104,BAKERSFIELD 2104,35597920,Residential,Home Construction,BAKERSFIELD,N/A,CC,Monitor Load,No,1,2025-09-12,72212.475954,"MULTILINESTRING ((862733.458 3916282.425, 8627..."
4,022331108,HUNTERS POINT (SF P) 1108,35461203,Residential,Home Construction,SF P (HUNTERS POINT),N/A,CC,Monitor Load,No,1,2025-09-12,22173.577880,"MULTILINESTRING ((552560.354 4178026.377, 5525..."

In [31]:
cust = pd.read_csv("../../../../../../capstone/electrigrid/data/utilities/pge_customer/PGE_2025_Q4_ElectricUsageByZip.csv")

In [32]:
cust.head()

,ZIPCODE,MONTH,YEAR,CUSTOMERCLASS,COMBINED,TOTALCUSTOMERS,TOTALKWH,AVERAGEKWH
0,93101,10,2025,Elec- Agricultural,Y,0,0,NaN
1,93101,11,2025,Elec- Agricultural,Y,0,0,NaN
2,93101,12,2025,Elec- Agricultural,Y,0,0,NaN
3,93110,10,2025,Elec- Agricultural,Y,0,0,NaN
4,93110,11,2025,Elec- Agricultural,Y,0,0,NaN

In [33]:
cust_q3 = pd.read_csv("../../../../../../capstone/electrigrid/data/utilities/pge_customer/PGE_2025_Q3_ElectricUsageByZip.csv")

In [34]:
cust_q3.head()

,ZIPCODE,MONTH,YEAR,CUSTOMERCLASS,COMBINED,TOTALCUSTOMERS,TOTALKWH,AVERAGEKWH
0,93101,7,2025,Elec- Agricultural,Y,0,0,NaN
1,93101,8,2025,Elec- Agricultural,Y,0,0,NaN
2,93101,9,2025,Elec- Agricultural,Y,0,0,NaN
3,93110,7,2025,Elec- Agricultural,Y,0,0,NaN
4,93110,8,2025,Elec- Agricultural,Y,0,0,NaN

In [36]:
feeder = gpd.read_file("../../../../../../capstone/electrigrid/data/utilities/pge_shapefiles/FeederDetail.shp")

In [37]:
feeder.head()

,Substation,FeederID,Feeder_Nam,Nominal_Vo,Load_Profi,ResCust,ComCust,IndCust,AgrCust,OthCust,Existing_D,Queued_DG,Total_DG,Division,VOLTNUM,Publish,Last_Updat,SHAPE_Leng,geometry
0,TIDEWATER,014652109,TIDEWATER 2109,21kV,No,5234,358,59,0,24,6930,330,7260,Diablo,21,1,2025-11-26,86845.803288,"MULTILINESTRING ((584539.020 4199128.622, 5845..."
1,HIGHWAY,042651101,HIGHWAY 1101,12kV,No,3895,134,18,2,0,9055,9583,18638,North Bay,12,1,2025-11-26,74254.171332,"MULTILINESTRING ((566168.901 4224379.534, 5661..."
2,DEL MONTE,182222104,DEL MONTE 2104,21kV,No,3932,757,221,10,0,9150,10999,20149,Central Coast,21,1,2025-10-10,220123.232719,"MULTILINESTRING ((604487.247 4049591.704, 6044..."
3,BERESFORD,024040404,BERESFORD 0404,4.16kV,No,1142,57,6,0,5,660,60,720,Peninsula,4,1,2025-11-11,10848.048592,"MULTILINESTRING ((559888.715 4157118.009, 5598..."
4,PURISIMA,182971101,PURISIMA 1101,12kV,No,2154,161,27,69,0,3182,3313,6495,Los Padres,12,1,2025-11-26,112280.712254,"MULTILINESTRING ((732980.593 3843685.000, 7329..."

In [39]:
feeder['total'] = feeder['ResCust'] + feeder['ComCust'] + feeder['IndCust'] + feeder['AgrCust'] + feeder['OthCust']

In [40]:
feeder['perc_res'] = feeder['ResCust'] / feeder['total'] * 100

In [41]:
feeder['perc_cust'] = feeder['ComCust'] / feeder['total'] * 100

In [42]:
feeder['perc_ind'] = feeder['IndCust'] / feeder['total'] * 100

In [43]:
feeder['perc_agr'] = feeder['AgrCust'] / feeder['total'] * 100

In [44]:
feeder['perc_oth'] = feeder['OthCust'] / feeder['total'] * 100

In [45]:
feeder.head()

,Substation,FeederID,Feeder_Nam,Nominal_Vo,Load_Profi,ResCust,ComCust,IndCust,AgrCust,OthCust,Existing_D,Queued_DG,Total_DG,Division,VOLTNUM,Publish,Last_Updat,SHAPE_Leng,geometry,total,perc_res,perc_cust,perc_ind,perc_agr,perc_oth
0,TIDEWATER,014652109,TIDEWATER 2109,21kV,No,5234,358,59,0,24,6930,330,7260,Diablo,21,1,2025-11-26,86845.803288,"MULTILINESTRING ((584539.020 4199128.622, 5845...",5675,92.229075,6.308370,1.039648,0.000000,0.422907
1,HIGHWAY,042651101,HIGHWAY 1101,12kV,No,3895,134,18,2,0,9055,9583,18638,North Bay,12,1,2025-11-26,74254.171332,"MULTILINESTRING ((566168.901 4224379.534, 5661...",4049,96.196592,3.309459,0.444554,0.049395,0.000000
2,DEL MONTE,182222104,DEL MONTE 2104,21kV,No,3932,757,221,10,0,9150,10999,20149,Central Coast,21,1,2025-10-10,220123.232719,"MULTILINESTRING ((604487.247 4049591.704, 6044...",4920,79.918699,15.386179,4.491870,0.203252,0.000000
3,BERESFORD,024040404,BERESFORD 0404,4.16kV,No,1142,57,6,0,5,660,60,720,Peninsula,4,1,2025-11-11,10848.048592,"MULTILINESTRING ((559888.715 4157118.009, 5598...",1210,94.380165,4.710744,0.495868,0.000000,0.413223
4,PURISIMA,182971101,PURISIMA 1101,12kV,No,2154,161,27,69,0,3182,3313,6495,Los Padres,12,1,2025-11-26,112280.712254,"MULTILINESTRING ((732980.593 3843685.000, 7329...",2411,89.340523,6.677727,1.119867,2.861883,0.000000